### ISSUE TITLE
vue-cli3 npm run build error   Scss is used, such as width: calc (100vh-20px). When I use NPM run build, the error is reported. There is no problem on cli2. Is it a configuration problem?

### ISSUE THREAD

**Issue by langxiaohui123** [intervolga/optimize-cssnano-plugin#11]
thanks 
/  Building for production...
With `useBuiltIns` option, required direct setting of `corejs` option

|  Building for production...
With `useBuiltIns` option, required direct setting of `corejs` option

 ERROR  Error: CSS minification error: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 100vh - 200PX
^..........^. File: assets/css/app.ef7adb30.css
Error: CSS minification error: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 100vh - 200PX
^..........^. File: assets/css/app.ef7adb30.css
    at D:\nodejs\node_global\jizhi3\node_modules\@intervolga\optimize-cssnano-plugin\index.js:106:21
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jizhi3@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jizhi3@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2019-03-21T10_04_56_806Z-debug.log

**Comment by ClintOxx** [comment]
@langxiaohui123 what did you do to fix this, i have the same error
