### ISSUE TITLE
Please support iOS css ‘constant’

### ISSUE THREAD

**Issue by zoosky** [intervolga/optimize-cssnano-plugin#3]
See https://github.com/framework7io/framework7/issues/2539 and

https://medium.com/@draganeror/iphone-x-layout-features-with-css-environment-variables-d57423433dec

**Comment by zoosky** [comment]
I guess this project cannot do anything about it. Same problem: 
 https://github.com/postcss/postcss-calc/issues/48

**Comment by MarvinXu** [comment]
I have the same issue with latest vue-cli

**Comment by MarvinXu** [comment]
I have the same issue with latest vue-cli

**Comment by max-preuschen** [comment]
@zoosky I have the same problem with Framework7 and and Vue CLI. Did you find a workaround to get rid of the CSS minification error? Was thinking about telling cssnano/postcss to ignore the framework7.css file, but not quite sure how to do it...

**Comment by natiz** [comment]
+1

**Comment by zoosky** [comment]
@umbertooo found this workaround:
https://github.com/vuejs/vue-cli/issues/2033#issuecomment-416713827
